### ISSUE TITLE
problemy z wyłączeniem wibracji i notyfikacjami

### ISSUE THREAD

**Issue by wojnicki** [barbarabod/SleepingBaby#15]
Poniżej 2 scenariousze prowadzące do powstania błędu.

Scenariusz 1:
1. naciśnięto: start
2. naciśnięto: child cry
3. naciśnięto: back
4. naciśnięto: stop
5. naciśnięto: start
6. counter 0:0 - ok
7. naciśnięto: back
8. po pewnym czasie (prawdopodbnie po upływie czasu z punktu 2) goto child notification i wibracje !!! - error: nie powinno się pokazać
9. po kliknieciu notyfikacji: 0:00 child cry, nie ma jak wyłączyć wibracji

Scenariusz 2:
1. naciśnięto: start
2. naciśnięto: cry child
3. naciśnięto: goto child notification - ok
4. naciśnięto: stop vibrating
5. naciśnięto: back
6. naciśnięto: stop
7. naciśnięto: start
8. counter 0:00 ok
9. naciśnięto: back
10. po pewnym czasie (prawdopodbnie po upływie czasu z punktu 4) time is up -leave child notification - error
11. nie ma jak wyłączyć wibracji

**Comment by michnam** [comment]
Problem pojawiał się ponieważ po zatrzymaniu działania aplikacji w tle (naciśnięcie przycisku stop), zatrzymywany był główny serwis, lecz do odmierzania czasu używany był CountDownTimer, który uruchamia się jako osoby serwis, więc mimo zatrzymanego głównego serwisu, timer nadal działał. 

Problem rozwiązany został poprzez zatrzymywanie timera przed zatrzymaniem głównego serwisu.

Błąd nie występuje już w żadnym z powyższych scenariuszy. Zmiany zostały wprowadzone w wersji 1.3 aplikacji.
